name: "Bug report"
description: "Report a bug you're experiencing on the Website
labels: "Type-Bug"
  assignees: "Aaron-Junker""
body:
- type: checkboxes
  attributes:
    options: 
      - label: "Related to a specific entry"
        required: true
- type: input
  attributes:
    label: "Url to where the issue occurs:"
  validations:
    required: false
- type: textarea
  attributes:
    label: "Describe the issue:"
  validations:
    required: true
