name: "Bug report"
description: "Report a bug you're experiencing on the Website"
labels: "Type-Bug"
assignees: "Aaron-Junker"
body:
- type: checkboxes
  label: "Related to a specific entry"
  required: true
- type: input
  label: "Url to where the issue occurs:"
  validations:
    required: false
- type: textarea
  label: "Describe the issue:"
  validations:
    required: true
