name: "Media file request"
description: "Suggest a media file to be added to the website"
labels: "Type-Request"
body:
- type: textarea
  attributes:
    label: "Describe the ident/ad/etc. that should be found (When was it broadcasted? Where? What was it?):"
  validations:
    required: true
